# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xml/PaintShapeSettingWidget.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PaintShapeSetting(object):
    def setupUi(self, PaintShapeSetting):
        PaintShapeSetting.setObjectName("PaintShapeSetting")
        PaintShapeSetting.resize(619, 606)
        self.verticalLayout = QtWidgets.QVBoxLayout(PaintShapeSetting)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(PaintShapeSetting)
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.unit = QtWidgets.QComboBox(PaintShapeSetting)
        self.unit.setObjectName("unit")
        self.unit.addItem("")
        self.unit.addItem("")
        self.horizontalLayout_2.addWidget(self.unit)
        self.label_4 = QtWidgets.QLabel(PaintShapeSetting)
        self.label_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.unit_pixel = QtWidgets.QSpinBox(PaintShapeSetting)
        self.unit_pixel.setMinimum(3)
        self.unit_pixel.setMaximum(20)
        self.unit_pixel.setObjectName("unit_pixel")
        self.horizontalLayout_2.addWidget(self.unit_pixel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(PaintShapeSetting)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(PaintShapeSetting)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.background_color = QtWidgets.QLineEdit(PaintShapeSetting)
        self.background_color.setObjectName("background_color")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.background_color)
        self.label_3 = QtWidgets.QLabel(PaintShapeSetting)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.font_size = QtWidgets.QSpinBox(PaintShapeSetting)
        self.font_size.setMinimum(16)
        self.font_size.setMaximum(60)
        self.font_size.setObjectName("font_size")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.font_size)
        self.label_5 = QtWidgets.QLabel(PaintShapeSetting)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.line_width = QtWidgets.QSpinBox(PaintShapeSetting)
        self.line_width.setMinimum(2)
        self.line_width.setMaximum(10)
        self.line_width.setObjectName("line_width")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_width)
        self.horizontalLayout_3.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(408, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 443, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(188, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.applyBtn = QtWidgets.QPushButton(PaintShapeSetting)
        self.applyBtn.setObjectName("applyBtn")
        self.horizontalLayout.addWidget(self.applyBtn)
        self.applayCloseBtn = QtWidgets.QPushButton(PaintShapeSetting)
        self.applayCloseBtn.setObjectName("applayCloseBtn")
        self.horizontalLayout.addWidget(self.applayCloseBtn)
        self.closeBtn = QtWidgets.QPushButton(PaintShapeSetting)
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout.addWidget(self.closeBtn)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(PaintShapeSetting)
        QtCore.QMetaObject.connectSlotsByName(PaintShapeSetting)

    def retranslateUi(self, PaintShapeSetting):
        _translate = QtCore.QCoreApplication.translate
        PaintShapeSetting.setWindowTitle(_translate("PaintShapeSetting", "PaintShapeSetting"))
        self.label.setText(_translate("PaintShapeSetting", "单位："))
        self.unit.setItemText(0, _translate("PaintShapeSetting", "mm"))
        self.unit.setItemText(1, _translate("PaintShapeSetting", "cm"))
        self.label_4.setText(_translate("PaintShapeSetting", "单位像素："))
        self.label_2.setText(_translate("PaintShapeSetting", "背景色："))
        self.background_color.setText(_translate("PaintShapeSetting", "ffffff"))
        self.label_3.setText(_translate("PaintShapeSetting", "字体尺寸："))
        self.label_5.setText(_translate("PaintShapeSetting", "线宽："))
        self.applyBtn.setText(_translate("PaintShapeSetting", "Apply"))
        self.applayCloseBtn.setText(_translate("PaintShapeSetting", "Apply&&Close"))
        self.closeBtn.setText(_translate("PaintShapeSetting", "Close"))

