# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xml/PluginManagerWidget.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PluginManagerWidget(object):
    def setupUi(self, PluginManagerWidget):
        PluginManagerWidget.setObjectName("PluginManagerWidget")
        PluginManagerWidget.resize(823, 802)
        PluginManagerWidget.setStyleSheet("#PluginManagerWidget{background-color:rgb(255, 255, 255)}")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(PluginManagerWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(PluginManagerWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.pluginListWraper = QtWidgets.QWidget()
        self.pluginListWraper.setGeometry(QtCore.QRect(0, 0, 451, 737))
        self.pluginListWraper.setStyleSheet("#pluginListWraper{background-color:rgb(255, 255, 255)}\n"
"#pluginList{background-color:rgb(255, 255, 255)}")
        self.pluginListWraper.setObjectName("pluginListWraper")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pluginListWraper)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pluginList = QtWidgets.QFrame(self.pluginListWraper)
        self.pluginList.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pluginList.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pluginList.setObjectName("pluginList")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pluginList)
        self.verticalLayout_2.setContentsMargins(0, 12, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3.addWidget(self.pluginList)
        spacerItem = QtWidgets.QSpacerItem(20, 720, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.scrollArea.setWidget(self.pluginListWraper)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.pluginDesc = QtWidgets.QFrame(PluginManagerWidget)
        self.pluginDesc.setStyleSheet("#pluginDesc{background-color:rgb(255, 255, 255)}")
        self.pluginDesc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pluginDesc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pluginDesc.setObjectName("pluginDesc")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.pluginDesc)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pluginName = QtWidgets.QLabel(self.pluginDesc)
        self.pluginName.setStyleSheet("font-size:36px")
        self.pluginName.setObjectName("pluginName")
        self.verticalLayout.addWidget(self.pluginName)
        self.label = QtWidgets.QLabel(self.pluginDesc)
        self.label.setStyleSheet("font-size:18px")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.description = QtWidgets.QLabel(self.pluginDesc)
        self.description.setStyleSheet("font-size:16px")
        self.description.setText("")
        self.description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.description.setWordWrap(True)
        self.description.setIndent(-2)
        self.description.setObjectName("description")
        self.verticalLayout.addWidget(self.description)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 13)
        self.horizontalLayout_3.addWidget(self.pluginDesc)
        self.horizontalLayout_3.setStretch(0, 4)
        self.horizontalLayout_3.setStretch(1, 3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(238, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.applyBtn = QtWidgets.QPushButton(PluginManagerWidget)
        self.applyBtn.setObjectName("applyBtn")
        self.horizontalLayout.addWidget(self.applyBtn)
        self.applyAndClose = QtWidgets.QPushButton(PluginManagerWidget)
        self.applyAndClose.setObjectName("applyAndClose")
        self.horizontalLayout.addWidget(self.applyAndClose)
        self.close = QtWidgets.QPushButton(PluginManagerWidget)
        self.close.setObjectName("close")
        self.horizontalLayout.addWidget(self.close)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)

        self.retranslateUi(PluginManagerWidget)
        QtCore.QMetaObject.connectSlotsByName(PluginManagerWidget)

    def retranslateUi(self, PluginManagerWidget):
        _translate = QtCore.QCoreApplication.translate
        PluginManagerWidget.setWindowTitle(_translate("PluginManagerWidget", "Form"))
        self.pluginName.setText(_translate("PluginManagerWidget", "TextLabel"))
        self.label.setText(_translate("PluginManagerWidget", "description:"))
        self.applyBtn.setText(_translate("PluginManagerWidget", "Apply"))
        self.applyAndClose.setText(_translate("PluginManagerWidget", "Apply&&Close"))
        self.close.setText(_translate("PluginManagerWidget", "Close"))

